"""init schema

Revision ID: 0367ebd7cf8e
Revises: 9ee138f386ff
Create Date: 2025-07-12 21:41:31.576929

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0367ebd7cf8e'
down_revision: Union[str, None] = '9ee138f386ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
