"""add updated_at to users

Revision ID: 2f9d15a0467f
Revises: e59ec4f82e0d
Create Date: 2025-07-19 12:35:23.242150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f9d15a0467f'
down_revision: Union[str, None] = 'e59ec4f82e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('debtors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('debtors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # Add 'role' as nullable with default
    op.add_column('users', sa.Column('role', sa.String(), nullable=True, server_default='user'))
    # Update existing rows (optional, but safe)
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    # Set NOT NULL constraint
    op.alter_column('users', 'role', nullable=False, server_default=None)
    # Add 'updated_at' as nullable
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('users', 'updated_at')
    op.alter_column('debtors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('debtors', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
