"""add created_at and updated_at to debtors

Revision ID: a74f7b1a15e7
Revises: 4480442fbf80
Create Date: 2025-07-19 13:36:45.144432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74f7b1a15e7'
down_revision: Union[str, None] = '4480442fbf80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable with default
    op.add_column('debtors', sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('now()')))
    op.add_column('debtors', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('now()')))
    # Fill existing nulls
    op.execute("UPDATE debtors SET created_at = now() WHERE created_at IS NULL")
    op.execute("UPDATE debtors SET updated_at = now() WHERE updated_at IS NULL")
    # Set NOT NULL
    op.alter_column('debtors', 'created_at', nullable=False)
    op.alter_column('debtors', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
