"""add created_at and updated_at defaults to debtors

Revision ID: a90c2dabf1a2
Revises: 2f9d15a0467f
Create Date: 2025-07-19 13:00:53.384897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a90c2dabf1a2'
down_revision: Union[str, None] = '2f9d15a0467f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Set default for updated_at in users
    op.alter_column('users', 'updated_at', server_default=sa.text('now()'))
    # Fill existing nulls before setting NOT NULL
    op.execute("UPDATE users SET updated_at = now() WHERE updated_at IS NULL")
    op.alter_column('users', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
