"""baseline

Revision ID: e59ec4f82e0d
Revises: ffe674569d1e
Create Date: 2025-07-12 21:45:20.833353

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e59ec4f82e0d'
down_revision: Union[str, None] = 'ffe674569d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
