"""init schema

Revision ID: ffe674569d1e
Revises: 0367ebd7cf8e
Create Date: 2025-07-12 21:41:55.779212

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ffe674569d1e'
down_revision: Union[str, None] = '0367ebd7cf8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
